### ISSUE TITLE
cli_parse not execute command on remote host

### ISSUE THREAD

**Issue by slefol** [ansible-collections/ansible.utils#347]
##### SUMMARY

the module ansible.utils.cli_parse fails on network device with error "/bin/sh: 1: show: not found\n".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cli_parse

##### ANSIBLE VERSION

```
ansible [core 2.16.5]
  config file = /home/ansible/ansible_network/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible-venv/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/ansible-venv/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/root/ansible-venv/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

```
Collection            Version
--------------------- -------
ansible.netcommon     6.0.0
ansible.posix         1.5.4
ansible.utils         3.1.0
community.general     8.5.0
```

##### OS / ENVIRONMENT

```
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_network_cli_ssh_type: paramiko
```
Cisco C2960, 12.2(55)SE12
Cisco C2960X, 15.2(7)E3
Cisco C9200L, 17.3.4

##### STEPS TO REPRODUCE

```
ansible sw-sl.montet -m ansible.utils.cli_parse -a '{"command":"show version","parser":{"name":"ansible.netcommon.native"}}' -i inventories/sites/
```

##### EXPECTED RESULTS

the module works as expected with ansible.utils colection v.2.12.2, 3.0.0
it doesnt't work with ansible.utils colection v.3.1.0 and 4.0.0

##### ACTUAL RESULTS

```
sw-sl.montet | FAILED! => {
    "changed": false,
    "msg": "/bin/sh: 1: show: not found\n",
    "stdout": "",
    "stdout_lines": []
}
```

**Comment by JeromeH27** [comment]
Hello,

I got a similar issue(with utils version 3.1.0 and upper).

My task:
    - name: Get IP/ARP Table
      ansible.utils.cli_parse:
        command: "show ip arp"
        parser:
          name: ansible.netcommon.pyats
          command: show ip arp
          os: iosxe
        set_fact: IP_ARP_TABLE
      ignore_errors: yes
      register: IP_ARP_TABLE_STATUS

The Error message is:
  {
    "msg": "/bin/sh: show: command not found\n",
    "stdout": "",
    "stdout_lines": [],
    "_ansible_no_log": false,
    "changed": false
  }

**Comment by janorga** [comment]
Same issue here. In my case, I checked that "ansible.utils" 3.1.0 (and later) breaks in the same way with this simple playbook as an example. From verbose output it seems that it tries to make an "standard" SSH call for a general purpose server system and using also the shell user, but not the user that playbook commands.

`- name: Get data
  gather_facts: false
  hosts: all
  become: yes
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.nxos.nxos
    ansible_become_method: enable
    ansible_user: admin
    ansible_command_timeout: 30

  tasks:

    - name: Parse interfaces output
      ansible.utils.cli_parse:
        command: show interface
        parser:
          os: cisco_nxos
          name: ansible.netcommon.ntc_templates
        set_fact: intf_parsed`


`TASK [Parse interfaces output] **********************************************************************************************
task path: /home/user/tmp/test.yaml:16
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
<host1> ESTABLISH LOCAL CONNECTION FOR USER: user
<host1> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-bfgavcdxnxgptlbsazrmsnoqzldogicw ; show interface'"'"' && sleep 0'
fatal: [host1]: FAILED! => {
    "changed": false,
    "msg": "/bin/sh: 1: show: not found\n",
    "stdout": "",
    "stdout_lines": []
}`

**Comment by janorga** [comment]
#357

**Comment by JeromeH27** [comment]
Hello,

by waiting the fix, as a workaround, I use this way:
  - 1 Use ios_command to execute a show command
  - 2 Parse the result with cli_parse with "text" argument

For instance:
    - name: Retrieve IP/ARP Table
      cisco.ios.ios_command:
        commands: show ip arp
      register: IP_ARP_TABLE_RAW_TEXT

    - name: Parse IP/ARP Table
      ansible.utils.cli_parse:
        text: "{{ IP_ARP_TABLE_RAW_TEXT.stdout[0] }}"
        parser:
          name: ansible.netcommon.pyats
          command: show ip arp
          os: ios
        set_fact: IP_ARP_TABLE
      ignore_errors: yes
      register: IP_ARP_TABLE_STATUS

For sure, it's not the best way to do but it works for me.

**Comment by NilashishC** [comment]
Resolved with #357

**Comment by iskadzul123** [comment]
Hi Team,

Issue seems to still persist on firmware 4.1. When will this be fixed ?

Collection                                     #139 Version
---------------------------------------- -------
amazon.aws                                         8.2.1  
ansible.netcommon                             6.1.3  
ansible.posix                                        1.6.2  
ansible.utils                                          4.1.0  

Error Message:
fatal: [R1]: FAILED! => {
    "changed": false,
    "msg": "/bin/sh: 1: show: not found\n",
    "stdout": "",
    "stdout_lines": []
}
